### ISSUE TITLE
cannot load harvested MARC into elasticsearch 5.6.4

### ISSUE THREAD

**Issue by zazi** [xbib/marc#2] opened 2017-12-06 15:08 UTC
* harvest MARCXML from http://www.bundeskunsthalle.de/cgi-bin/bib/oai-pmh
* transform it to binary with help of yaz-marcdump
* load it into an elasticsearch 5.6.4 instance with help of esbulk

=> following error will be found in elasticsearch log
`Caused by: java.lang.IllegalArgumentException: object field starting or ending with a [.] makes object resolution ambiguous: [ ]
        at org.elasticsearch.index.mapper.DocumentParser.splitAndValidatePath(DocumentParser.java:183) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.getMapper(DocumentParser.java:938) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:589) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:396) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:373) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:465) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:484) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:570) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:526) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:385) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:373) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:465) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:484) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:570) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:526) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:385) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:373) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:66) ~[elasticsearch-5.6.4.jar:5.6.4]
        ... 30 more`

**Comment by jprante** [comment] 2017-12-07 09:15
Thanks for the data.

The JSON data generated which is not accepted by Elasticsearch has double keys (Bundeskunsthalle record ID 048861) and looks like

```
  "600": [
    {
      "07": [
        {
          "a": "Supports."
        }
      ]
    },
    {
      "07": [
        {
          "a": "."
        },
        {
          " ": "Surfaces <Künstlergemeinschaft>"
        }
      ]
    }
  ],
```

The double indicator "07" is rejected. The solution is by joining repeated indicators into a single "07" sequence, I think I can add a fix to the next version.

**Comment by jprante** [comment] 2017-12-07 09:51
For the record, the original XML data looks like

```
    <datafield tag="600" ind1="0" ind2="7">
        <subfield code="a">Supports.</subfield>
    </datafield>
    <datafield tag="600" ind1="0" ind2="7">
        <subfield code="a">.</subfield>
        <subfield code=" ">Surfaces &lt;Künstlergemeinschaft&gt;</subfield>
    </datafield>
```

**Comment by zazi** [comment] 2017-12-07 10:47
> The double indicator "07" is rejected.

ok, then the error message is a bit misleading, or? ;)

**Comment by zazi** [comment] 2017-12-07 10:48
on the other side, then it looks like that information will be joined that should be separated, or?

**Comment by zazi** [comment] 2017-12-07 10:50
if you join "07" occurrences, then you also need to join the "a" occurrences below ...

**Comment by jprante** [comment] 2017-12-07 12:31
I'm still surprised Elasticsearch 5+ does not accept the multiple occurences. Elasticsearch 2 accepts without error.

**Comment by jprante** [comment] 2017-12-07 12:42
Seems like an Elasticsearch bug introduced between 5.2.0 and 5.2.1

**Comment by jprante** [comment] 2017-12-07 12:46
Looks like a regression. There was a fix for empty field names, probably related to this issue https://github.com/elastic/elasticsearch/pull/22891

**Comment by zazi** [comment] 2017-12-07 12:58
so a solution might be to replace empty "code" keys with "_", or? (as you already do it with ind1 and ind2)

**Comment by jprante** [comment] 2017-12-07 13:06
Yes, it looks like space field names and empty field names are forbidden now. Replacing with underscore seems the best idea. (So the double "07" is ok, my fault).

**Comment by jprante** [comment] 2017-12-07 13:07
On the other hand, I will report this to Elasticsearch in the hope they can re-enable space field names.

**Comment by jprante** [comment] 2017-12-07 17:28
Closed by https://github.com/xbib/marc/commit/58c2a49293af4b91f2ebc00bc964e5c43b344585

**Closed by jprante** 2017-12-07 17:28 UTC

**Comment by zazi** [comment] 2017-12-08 11:35
thx a lot, Sir!

**Comment by zazi** [comment] 2017-12-08 15:28
works fine for data from GBV and Bundeskunsthalle.

**Comment by jprante** [comment] 2017-12-12 09:24
FWIW Elasticsearch has confirmed, using JSON space field names is no longer allowed since 5.2.1. It was just a poor error message. A precise error message has been added to current Elasticsearch versions and xbib MARC will continue to replace space by underscore.
